### ISSUE TITLE
Could not identify the intended function with name `balanceOf`

### ISSUE THREAD

**Issue by gasse4life** [cusdt-LINK/alpha-kcc-dex-bot#1]
hi dear,
awesome script.

im getting this error.

ERROR: 2022-03-01 01:32:53,403 
Could not identify the intended function with name `balanceOf`, positional argument(s) of type `(<class 'str'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `balanceOf`: ['balanceOf(address)']
Function invocation failed due to no matching argument types.
Traceback (most recent call last):
  File "C:\Users\PAPA\Desktop\KCC\bot\AlphaBot.py", line 4630, in run
    token['_TOKEN_BALANCE'] = check_balance(token['ADDRESS'], token['SYMBOL'], display_quantity=False) / token['_CONTRACT_DECIMALS']
  File "C:\Users\PAPA\Desktop\KCC\bot\AlphaBot.py", line 2201, in check_balance
    balance = balanceContract.functions.balanceOf(settings['WALLETADDRESS']).call()
  File "C:\Users\PAPA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\contract.py", line 878, in __call__
    clone._set_function_info()
  File "C:\Users\PAPA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\contract.py", line 883, in _set_function_info
    self.abi = find_matching_fn_abi(
  File "C:\Users\PAPA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\_utils\contracts.py", line 163, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `balanceOf`, positional argument(s) of type `(<class 'str'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `balanceOf`: ['balanceOf(address)']
Function invocation failed due to no matching argument types.

**Comment by gweidart** [comment]
> hi dear, awesome script.
> 
> im getting this error.
> 
> ERROR: 2022-03-01 01:32:53,403 Could not identify the intended function with name `balanceOf`, positional argument(s) of type `(<class 'str'>,)` and keyword argument(s) of type `{}`. Found 1 function(s) with the name `balanceOf`: ['balanceOf(address)'] Function invocation failed due to no matching argument types. Traceback (most recent call last): File "C:\Users\PAPA\Desktop\KCC\bot\AlphaBot.py", line 4630, in run token['_TOKEN_BALANCE'] = check_balance(token['ADDRESS'], token['SYMBOL'], display_quantity=False) / token['_CONTRACT_DECIMALS'] File "C:\Users\PAPA\Desktop\KCC\bot\AlphaBot.py", line 2201, in check_balance balance = balanceContract.functions.balanceOf(settings['WALLETADDRESS']).call() File "C:\Users\PAPA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\contract.py", line 878, in **call** clone._set_function_info() File "C:\Users\PAPA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\contract.py", line 883, in _set_function_info self.abi = find_matching_fn_abi( File "C:\Users\PAPA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3_utils\contracts.py", line 163, in find_matching_fn_abi raise ValidationError(message) web3.exceptions.ValidationError: Could not identify the intended function with name `balanceOf`, positional argument(s) of type `(<class 'str'>,)` and keyword argument(s) of type `{}`. Found 1 function(s) with the name `balanceOf`: ['balanceOf(address)'] Function invocation failed due to no matching argument types.

Fixed in the latest update. I just pushed [major update v1.0.1](https://github.com/cusdt-LINK/alpha-kcc-dex-bot/commit/99be8ddc944e58c7049d7cfd3301153e2d99bb15).  Please clone or download the repo and run the new source or .exe. 

- Various bug fixes (ui & ux)

- Speed optimizations (this is seriously the fastest this bot has ever been!)

- You can now reload Tokens.json in real time.

- Added support for AlphaSwap (KCC), Harmony network, Cronos network, ETH testnet, Metis Network.

- Added Pinksale sniping

- Added support for Apprise notifications!

Users can now receive notifications in real time when AlphaBot makes a trade.

Apprise supports SMS/ iMessage / in-browser / Telegram / Discord... basically any type of notifications!
