### ISSUE TITLE
Trade error 

### ISSUE THREAD

**Issue by shakilkhan1801** [cusdt-LINK/alpha-kcc-dex-bot#12]
2023-06-04 10:24:53.364964 Current Gas Price = 0.007085924
2023-06-04 10:24:53.364964 Transaction for WETH will be created with gas = 0.007085924
2023-06-04 10:24:53.364964
2023-06-04 10:24:54.029546 Found 820.0378 liquidity for WETH/UNI
2023-06-04 10:24:54.483094 --------------------------------------------------------------
2023-06-04 10:24:54.483094 Sell Signal Found =-= Sell Signal Found =-= Sell Signal Found 
2023-06-04 10:24:54.483094
2023-06-04 10:24:54.483094 Sell price in WETH/UNI : 23.717447970859939943
2023-06-04 10:24:54.488736 --------------------------------------------------------------
2023-06-04 10:24:56.348186 Current WETH Liquidity = 117160.994916 $
2023-06-04 10:24:56.348186 MINIMUM_LIQUIDITY_IN_DOLLARS parameter = 1  --> Enough liquidity detected : 
let's go!
2023-06-04 10:24:56.348186 Placing Sell Order WETH
2023-06-04 10:24:56.610802 Current Wallet Balance is:  0.1465 WETH
2023-06-04 10:24:57.383425 Transaction Hash =  0xc325938c608e3b9a3b9c1a2aff935c1e26e5d92a47733e08387ea37191dc58bc
2023-06-04 10:24:57.383425 Checking for transaction confirmation (waiting 60 seconds)...........................
2023-06-04 10:25:58.627707 --------------------------------
2023-06-04 10:25:58.628695    SELL TRANSACTION FAILURE !
2023-06-04 10:25:58.628695 --------------------------------
2023-06-04 10:25:58.629694 Type of failures and possible causes:
2023-06-04 10:25:58.629694 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 
1000000 at least
2023-06-04 10:25:58.630694 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. AlphaBot will check approval right now.
2023-06-04 10:25:58.631694 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
2023-06-04 10:25:58.631694 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
2023-06-04 10:25:58.632692 - TRANSFER_FAILED              --> There is a whitelist
2023-06-04 10:25:58.633692 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds in your wallet to cover fees
2023-06-04 10:25:58.633692 - ... or your node is not functioning properly
2023-06-04 10:25:58.634692 -------------------------------
2023-06-04 10:25:58.634692 Checking Approval Status 0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6
2023-06-04 10:25:58.861437 Token is already approved --> AlphaBot can use this token 
2023-06-04 10:25:59.095988 WETH/UNI Price: 23.717447970859939943011341 UNI - Buy: 0.04092 Sell: 0 Stop: 0 - Token balance: 0.1465 (= 3.47 UNI)
2023-06-04 10:25:59.314681 --------------------------------------------------------------
2023-06-04 10:25:59.314681 Sell Signal Found =-= Sell Signal Found =-= Sell Signal Found 
2023-06-04 10:25:59.314681
2023-06-04 10:25:59.314681 Sell price in WETH/UNI : 23.717447970859939943
2023-06-04 10:25:59.314681 --------------------------------------------------------------
2023-06-04 10:26:00.010120 Current WETH Liquidity = 117160.994916 $
2023-06-04 10:26:00.025746 MINIMUM_LIQUIDITY_IN_DOLLARS parameter = 1  --> Enough liquidity detected : 
let's go!
2023-06-04 10:26:00.025746 Placing Sell Order WETH
2023-06-04 10:26:00.263421 Current Wallet Balance is:  0.1465 WETH
2023-06-04 10:26:00.817478 Transaction Hash =  0xbf9bde1531d6ee87b1f64838e94c352ce718f5260473b1486289261c19577a67
2023-06-04 10:26:00.817478 Checking for transaction confirmation (waiting 60 seconds)...........................
2023-06-04 10:27:01.080950 --------------------------------
2023-06-04 10:27:01.082937    SELL TRANSACTION FAILURE !
2023-06-04 10:27:01.083951 --------------------------------
2023-06-04 10:27:01.083951 Type of failures and possible causes:
2023-06-04 10:27:01.084934 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 
1000000 at least
2023-06-04 10:27:01.085934 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. AlphaBot will check approval right now.
2023-06-04 10:27:01.086932 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
2023-06-04 10:27:01.087933 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
2023-06-04 10:27:01.088932 - TRANSFER_FAILED              --> There is a whitelist
2023-06-04 10:27:01.089931 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds in your wallet to cover fees
2023-06-04 10:27:01.090931 - ... or your node is not functioning properly
2023-06-04 10:27:01.090931 -------------------------------

**Comment by swiftcode10** [comment]
hello pls how do you configure the code , i ran the command to run the bot but got this error .

 /Alpha/alpha-kcc-dex-bot$ python3 AlphaBot.py
Traceback (most recent call last):
  File "/home/chibuike/Alpha/alpha-kcc-dex-bot/AlphaBot.py", line 4, in <module>
    import pause
ModuleNotFoundError: No module named 'pause'

**Comment by gweidart** [comment]
> hello pls how do you configure the code , i ran the command to run the bot but got this error .
> 
> /Alpha/alpha-kcc-dex-bot$ python3 AlphaBot.py Traceback (most recent call last): File "/home/chibuike/Alpha/alpha-kcc-dex-bot/AlphaBot.py", line 4, in import pause ModuleNotFoundError: No module named 'pause'

pip install pause

**Comment by swiftcode10** [comment]
Hello bro /pls I’m about to deposit some eth before I run the alpha bot
I’ve fix the repo, hmm pls I would like to know is this repo profitable,
since u have used it how much potentially can I make from it , pls
generously brife me
